name: Continuous Deployment

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

env:
  NODE_VERSION: 18.7.0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Clean package
        run: ./clean.sh

      - name: Build package
        run: ./build.sh

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: amplify-${{ steps.date.outputs.date }}
          path: 'app/*.zip'

  publish:
    name: Publish
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@salesforce-misc'

      - name: Set up NPM authentication
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" >> .npmrc

      - name: Set up NPM registry
        run: echo "registry=https://npm.pkg.github.com/@salesforce-misc/Data-Lake-for-Nonprofit-Cloud" >> .npmrc

      - name: Set up NPM auth
        run: echo "always-auth=true" >> .npmrc

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: amplify-${{ steps.date.outputs.date }}

      - name: Create version
        run: git config --global user.email "simsek97@gmail.com" && git config --global user.name "Simsek Mert" && yarn version --patch

      - name: Get latest tag
        id: tag-version
        run: echo "::set-output name=LATEST_TAG::$(git describe --abbrev=0 --tags)"

      - name: Rename amplify artifact
        run: mv amplify.zip amplify-${{ steps.tag-version.outputs.LATEST_TAG }}.zip

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        with:
          artifacts: '*.zip'
          tag: ${{ steps.tag-version.outputs.LATEST_TAG }}
          name: Release ${{ steps.tag-version.outputs.LATEST_TAG }}
          draft: false
          prerelease: false
